FROM apache/airflow:2.9.3-python3.11

USER root

RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-25.0.5.tgz \
    | tar xz -C /usr/local/bin --strip-components=1 docker/docker \
    && groupadd -f docker \
    && usermod -aG docker airflow

USER airflow

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

